# Generated by Django 4.1.4 on 2023-01-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField(default=18)),
                ("course", models.CharField(max_length=200)),
                ("reported", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
